import type { NextApiRequest, NextApiResponse } from 'next';
import JSZip from 'jszip';

function getFs() { return require('fs') as typeof import('fs'); }
function getPath() { return require('path') as typeof import('path'); }

function refsDir() {
  return process.env.REFS_DIR ?? '/no-local-refs';
}

function hasLocalRefs(): boolean {
  if (!process.env.REFS_DIR) return false;
  try { const fs = getFs(); const rd = refsDir(); return fs.existsSync(rd) && fs.statSync(rd).isDirectory(); } catch { return false; }
}

const HF_URL = (process.env.HF_BUCKET_URL ?? 'https://huggingface.co/buckets/SecretITis/Theme-Studio/resolve').replace(/\/$/, '');
const MANIFEST_URL = process.env.HF_MANIFEST_URL ?? `${HF_URL}/manifest.json`;

interface AppEntry { id: string; name: string; developer: string; icon: string | null; screens: string[]; }
interface CatEntry { id: string; label: string; appCount: number; preview: string; apps: AppEntry[]; }
interface Manifest { categories: CatEntry[]; }

async function fetchManifest(): Promise<Manifest | null> {
  try {
    const res = await fetch(MANIFEST_URL, { cache: 'no-store' } as RequestInit);
    if (!res.ok) return null;
    return await res.json() as Manifest;
  } catch { return null; }
}

function buildClaudePrompt(category: string, apps: { name: string; developer: string; screens: string[] }[]): string {
  const imageLines = apps.flatMap(a =>
    a.screens.map(s => `  ${HF_URL}/${category}/${a.name.toLowerCase().replace(/\s+/g, '-')}/${s}`)
  ).slice(0, 30).join('\n');

  return `# Android UI Reference Pack — ${category}
Generated by JISL Theme Engine · ${new Date().toISOString().split('T')[0]}

These screenshots are design references only — they show layout patterns, color palettes,
typography choices, and UI component arrangements from real apps.

## Apps included
${apps.map(a => `- ${a.name}${a.developer ? ` by ${a.developer}` : ''} (${a.screens.length} screens)`).join('\n')}

## Reference image URLs (HuggingFace)
${imageLines}

---

## Claude Code prompt — paste this with your own content

I'm building an Android app and I have reference screenshots from the ${category} category.
Please help me implement a similar layout using:
1. The structural patterns from these screenshots (navigation, cards, lists, hero sections)
2. Replace ALL reference images/screenshots with my own branded images and content
3. Apply the JISL theme tokens for colors, typography, and spacing
4. Do NOT copy any app content, logos, or copyrighted imagery

Focus on:
- Layout structure and spacing
- Component patterns (bottom nav, cards, stat rows, search bars)
- Visual hierarchy and typography scale
- Color usage patterns (primary actions, secondary content, backgrounds)

Important: Replace every reference image with your own content. Use the layout as a template, not a copy.
`;
}

function addAppToZip(zipFolder: JSZip, appDir: string, appName: string) {
  const fs   = getFs();
  const path = getPath();
  const appFolder = zipFolder.folder(appName)!;
  const files = fs.readdirSync(appDir) as string[];

  const metaFile = path.join(appDir, 'meta.json');
  if (fs.existsSync(metaFile)) appFolder.file('meta.json', fs.readFileSync(metaFile));

  const iconFile = files.find((f: string) => f === 'icon.jpg' || f === 'icon.png');
  if (iconFile) appFolder.file(iconFile, fs.readFileSync(path.join(appDir, iconFile)));

  const screens = files.filter((f: string) => f.startsWith('screen-') && (f.endsWith('.jpg') || f.endsWith('.png'))).sort();
  for (const screen of screens) appFolder.file(screen, fs.readFileSync(path.join(appDir, screen)));
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { category, app } = req.query;
  if (!category) return res.status(400).send('Specify category or category+app');

  const zip = new JSZip();

  // ── Remote / Vercel: build ZIP with Claude prompt + image URLs ───────────────
  if (!hasLocalRefs()) {
    const manifest = await fetchManifest();
    if (!manifest) return res.status(503).send('Could not load manifest');

    const cat = manifest.categories.find(c => c.id === category);
    if (!cat) return res.status(404).send('Category not found');

    if (app) {
      const appEntry = cat.apps.find(a => a.id === app);
      if (!appEntry) return res.status(404).send('App not found');

      const prompt = buildClaudePrompt(cat.id, [{
        name: appEntry.name,
        developer: appEntry.developer,
        screens: appEntry.screens,
      }]);
      zip.file('CLAUDE_PROMPT.txt', prompt);
      zip.file('image_urls.txt', appEntry.screens
        .map(s => `${HF_URL}/${cat.id}/${appEntry.id}/${s}`)
        .join('\n'));

      const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', `attachment; filename="${appEntry.id}-reference.zip"`);
      return res.send(buf);
    }

    // Category download — include top 10 apps' prompts + URL list
    const appsSlice = cat.apps.slice(0, 10);
    const prompt = buildClaudePrompt(cat.id, appsSlice.map(a => ({
      name: a.name,
      developer: a.developer,
      screens: a.screens,
    })));
    zip.file('CLAUDE_PROMPT.txt', prompt);
    zip.file('image_urls.txt', appsSlice.flatMap(a =>
      a.screens.map(s => `${HF_URL}/${cat.id}/${a.id}/${s}`)
    ).join('\n'));
    const metaLines = appsSlice.map(a =>
      JSON.stringify({ id: a.id, name: a.name, developer: a.developer, screenCount: a.screens.length })
    ).join('\n');
    zip.file('apps_meta.jsonl', metaLines);

    const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${category}-references.zip"`);
    return res.send(buf);
  }

  // ── Local dev: read from disk ────────────────────────────────────────────────
  const fs   = getFs();
  const path = getPath();
  const rd   = refsDir();

  if (app) {
    const appDir = path.join(rd, category as string, app as string);
    if (!fs.existsSync(appDir)) return res.status(404).send('App not found');
    const appFolder = zip.folder(app as string)!;
    addAppToZip(appFolder, appDir, app as string);
    const prompt = buildClaudePrompt(category as string, [{
      name: app as string, developer: '', screens:
        (fs.readdirSync(appDir) as string[]).filter((f: string) => f.startsWith('screen-') && (f.endsWith('.jpg') || f.endsWith('.png'))).sort(),
    }]);
    zip.file('CLAUDE_PROMPT.txt', prompt);
    const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${app}-reference.zip"`);
    return res.send(buf);
  }

  const catDir = path.join(rd, category as string);
  if (!fs.existsSync(catDir)) return res.status(404).send('Category not found');
  const catFolder = zip.folder(category as string)!;
  const apps = (fs.readdirSync(catDir) as string[])
    .filter((n: string) => { try { return fs.statSync(path.join(catDir, n)).isDirectory(); } catch { return false; } })
    .slice(0, 10);
  for (const a of apps) addAppToZip(catFolder, path.join(catDir, a), a);
  const prompt = buildClaudePrompt(category as string, apps.map(a => ({
    name: a, developer: '',
    screens: (fs.readdirSync(path.join(catDir, a)) as string[]).filter((f: string) => f.startsWith('screen-') && (f.endsWith('.jpg') || f.endsWith('.png'))).sort(),
  })));
  zip.file('CLAUDE_PROMPT.txt', prompt);
  const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${category}-references.zip"`);
  return res.send(buf);
}
