import type { NextApiRequest, NextApiResponse } from 'next';
import JSZip from 'jszip';

function getFs() { return require('fs') as typeof import('fs'); }
function getPath() { return require('path') as typeof import('path'); }

function refsDir() { return process.env.REFS_DIR ?? '/no-local-refs'; }
function hasLocalRefs(): boolean {
  if (!process.env.REFS_DIR) return false;
  try { const fs = getFs(); const rd = refsDir(); return fs.existsSync(rd) && fs.statSync(rd).isDirectory(); } catch { return false; }
}

const HF_URL = (process.env.HF_BUCKET_URL ?? 'https://huggingface.co/buckets/SecretITis/Theme-Studio/resolve').replace(/\/$/, '');
const MANIFEST_URL = process.env.HF_MANIFEST_URL ?? `${HF_URL}/manifest.json`;

// Server-side manifest cache (lives for the duration of the lambda warm instance)
let manifestCache: Manifest | null = null;
let manifestFetchedAt = 0;
const MANIFEST_TTL = 10 * 60 * 1000; // 10 min

interface AppEntry { id: string; name: string; developer: string; icon: string | null; screens: string[]; }
interface CatEntry { id: string; label: string; appCount: number; preview: string; apps: AppEntry[]; }
interface Manifest { categories: CatEntry[]; }

async function fetchManifest(): Promise<Manifest | null> {
  const now = Date.now();
  if (manifestCache && now - manifestFetchedAt < MANIFEST_TTL) return manifestCache;
  try {
    const res = await fetch(MANIFEST_URL, { cache: 'no-store' } as RequestInit);
    if (!res.ok) return null;
    manifestCache = await res.json() as Manifest;
    manifestFetchedAt = now;
    return manifestCache;
  } catch { return null; }
}

// Fetch one image from HF with a timeout so a single slow image doesn't kill the whole ZIP
async function fetchImage(url: string): Promise<Buffer | null> {
  try {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 8000);
    const res = await fetch(url, { signal: ctrl.signal });
    clearTimeout(timer);
    if (!res.ok) return null;
    return Buffer.from(await res.arrayBuffer());
  } catch { return null; }
}

function buildClaudePrompt(category: string, apps: { name: string; developer: string; id: string; screens: string[] }[]): string {
  return `# Android UI Reference Pack — ${category}
Generated by JISL Theme Engine · ${new Date().toISOString().split('T')[0]}

These screenshots are design references only — they show layout patterns, color palettes,
typography choices, and UI component arrangements from real apps.

## Apps included
${apps.map(a => `- ${a.name}${a.developer ? ` by ${a.developer}` : ''} (${a.screens.length} screens)`).join('\n')}

---

## Instructions for Claude Code

I'm building an Android app and I have reference screenshots in the attached images/ folder.
Please help me implement a similar layout using:
1. The structural patterns from these screenshots (navigation, cards, lists, hero sections)
2. Replace ALL reference images/screenshots with my own branded images and content
3. Apply the JISL theme tokens for colors, typography, and spacing
4. Do NOT copy any app content, logos, or copyrighted imagery

Focus on:
- Layout structure and spacing
- Component patterns (bottom nav, cards, stat rows, search bars)
- Visual hierarchy and typography scale
- Color usage patterns (primary actions, secondary content, backgrounds)

Important: Replace every reference image with your own content. Use the layout as a template, not a copy.
`;
}

function addLocalAppToZip(appFolder: JSZip, appDir: string) {
  const fs   = getFs();
  const path = getPath();
  const files = fs.readdirSync(appDir) as string[];
  const metaFile = path.join(appDir, 'meta.json');
  if (fs.existsSync(metaFile)) appFolder.file('meta.json', fs.readFileSync(metaFile));
  const iconFile = files.find((f: string) => f === 'icon.jpg' || f === 'icon.png');
  if (iconFile) appFolder.file(iconFile, fs.readFileSync(path.join(appDir, iconFile)));
  const screens = files.filter((f: string) => f.startsWith('screen-') && (f.endsWith('.jpg') || f.endsWith('.png'))).sort();
  for (const s of screens) appFolder.file(s, fs.readFileSync(path.join(appDir, s)));
}

// Max screens fetched per app to stay within Vercel's 30s function timeout
const MAX_SCREENS_PER_APP = 5;
const MAX_APPS_CATEGORY   = 5;

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { category, app } = req.query;
  if (!category) return res.status(400).send('Specify category or category+app');

  const zip = new JSZip();

  // ── Remote / Vercel: fetch real images from HuggingFace ─────────────────────
  if (!hasLocalRefs()) {
    const manifest = await fetchManifest();
    if (!manifest) return res.status(503).send('Could not load manifest');

    const cat = manifest.categories.find(c => c.id === category);
    if (!cat) return res.status(404).send('Category not found');

    if (app) {
      // Single app download
      const appEntry = cat.apps.find(a => a.id === app);
      if (!appEntry) return res.status(404).send('App not found');

      const imagesFolder = zip.folder('images')!;
      const screensToFetch = appEntry.screens.slice(0, MAX_SCREENS_PER_APP);

      // Fetch icon + screens in parallel
      const fetches: Promise<void>[] = [];
      if (appEntry.icon) {
        fetches.push(fetchImage(`${HF_URL}/${cat.id}/${appEntry.id}/${appEntry.icon}`).then(buf => {
          if (buf) imagesFolder.file(appEntry.icon!, buf);
        }));
      }
      for (const screen of screensToFetch) {
        fetches.push(fetchImage(`${HF_URL}/${cat.id}/${appEntry.id}/${screen}`).then(buf => {
          if (buf) imagesFolder.file(screen, buf);
        }));
      }
      await Promise.all(fetches);

      zip.file('CLAUDE_PROMPT.txt', buildClaudePrompt(cat.id, [{
        id: appEntry.id, name: appEntry.name, developer: appEntry.developer, screens: screensToFetch,
      }]));
      zip.file('meta.json', JSON.stringify({ id: appEntry.id, name: appEntry.name, developer: appEntry.developer, screenCount: appEntry.screens.length }, null, 2));

      const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
      res.setHeader('Content-Type', 'application/zip');
      res.setHeader('Content-Disposition', `attachment; filename="${appEntry.id}-reference.zip"`);
      return res.send(buf);
    }

    // Category download — top N apps, capped screens each
    const appsSlice = cat.apps.slice(0, MAX_APPS_CATEGORY);
    const fetches: Promise<void>[] = [];

    for (const appEntry of appsSlice) {
      const appFolder = zip.folder(`images/${appEntry.id}`)!;
      const screensToFetch = appEntry.screens.slice(0, MAX_SCREENS_PER_APP);
      if (appEntry.icon) {
        fetches.push(fetchImage(`${HF_URL}/${cat.id}/${appEntry.id}/${appEntry.icon}`).then(buf => {
          if (buf) appFolder.file(appEntry.icon!, buf);
        }));
      }
      for (const screen of screensToFetch) {
        fetches.push(fetchImage(`${HF_URL}/${cat.id}/${appEntry.id}/${screen}`).then(buf => {
          if (buf) appFolder.file(screen, buf);
        }));
      }
    }
    await Promise.all(fetches);

    zip.file('CLAUDE_PROMPT.txt', buildClaudePrompt(cat.id, appsSlice.map(a => ({
      id: a.id, name: a.name, developer: a.developer, screens: a.screens.slice(0, MAX_SCREENS_PER_APP),
    }))));
    zip.file('apps_meta.json', JSON.stringify(appsSlice.map(a => ({
      id: a.id, name: a.name, developer: a.developer, totalScreens: a.screens.length,
    })), null, 2));

    const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${category}-references.zip"`);
    return res.send(buf);
  }

  // ── Local dev: read from disk ────────────────────────────────────────────────
  const fs   = getFs();
  const path = getPath();
  const rd   = refsDir();

  if (app) {
    const appDir = path.join(rd, category as string, app as string);
    if (!fs.existsSync(appDir)) return res.status(404).send('App not found');
    const appFolder = zip.folder('images')!;
    addLocalAppToZip(appFolder, appDir);
    zip.file('CLAUDE_PROMPT.txt', buildClaudePrompt(category as string, [{
      id: app as string, name: app as string, developer: '',
      screens: (fs.readdirSync(appDir) as string[]).filter((f: string) => f.startsWith('screen-') && (f.endsWith('.jpg') || f.endsWith('.png'))).sort(),
    }]));
    const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${app}-reference.zip"`);
    return res.send(buf);
  }

  const catDir = path.join(rd, category as string);
  if (!fs.existsSync(catDir)) return res.status(404).send('Category not found');
  const apps = (fs.readdirSync(catDir) as string[])
    .filter((n: string) => { try { return fs.statSync(path.join(catDir, n)).isDirectory(); } catch { return false; } })
    .slice(0, MAX_APPS_CATEGORY);
  for (const a of apps) addLocalAppToZip(zip.folder(`images/${a}`)!, path.join(catDir, a));
  zip.file('CLAUDE_PROMPT.txt', buildClaudePrompt(category as string, apps.map(a => ({
    id: a, name: a, developer: '',
    screens: (fs.readdirSync(path.join(catDir, a)) as string[]).filter((f: string) => f.startsWith('screen-') && (f.endsWith('.jpg') || f.endsWith('.png'))).sort(),
  }))));
  const buf = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 6 } });
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Disposition', `attachment; filename="${category}-references.zip"`);
  return res.send(buf);
}
