import type { Theme } from '../types';

// Inspired by AAVE Save & Earn — deep navy/purple, glowing lavender charts,
// large bold balance numbers, minimal bottom tab nav, dark consumer fintech aesthetic.

const theme: Theme = {
  id: 'aave-dark',
  name: 'Aave Dark',
  description: 'Deep navy DeFi fintech — glowing purple charts, bold balance display, minimal bottom tabs. Inspired by savings & earn mobile apps.',
  category: 'finance',
  tags: ['finance', 'dark', 'mobile', 'defi', 'crypto', 'navy', 'purple', 'consumer'],
  brand: {
    name: 'Aave Dark',
    tagline: 'Earn more, effortlessly.',
    logo: '',
    logoAlt: 'Aave Dark',
    favicon: '',
    stripeColors: ['#B388FF', '#1A1433', '#7C4DFF', '#1A1433', '#B388FF'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#0D0B1E',
    bgSecondary: '#130F2A',
    bgTertiary: '#1A1433',
    panel: '#1E1740',
    panelSecondary: '#251D4E',
    tint: 'rgba(179,136,255,0.10)',
    ink: '#FFFFFF',
    ink2: '#B0A8CC',
    ink3: '#6B6189',
    rule: '#2A2350',
    ruleStrong: '#3D3470',
    primary: '#B388FF',
    primaryHover: '#9C5FF7',
    primaryText: '#0D0B1E',
    accent1: '#B388FF',
    accent2: '#69F0AE',
    accent3: '#FFD54F',
    accent4: '#40C4FF',
    accent5: '#FF6E6E',
    alert: '#FF6E6E',
    warn: '#FFD54F',
    ok: '#69F0AE',
    info: '#40C4FF',
    navBg: '#0D0B1E',
    navText: '#6B6189',
    navActiveText: '#B388FF',
    navActiveBg: 'rgba(179,136,255,0.12)',
    navActiveBorder: '#B388FF',
    headerBg: '#0D0B1E',
    headerText: '#FFFFFF',
    headerBorder: '#2A2350',
    buttonGradient: 'linear-gradient(135deg, #B388FF 0%, #7C4DFF 100%)',
    buttonGlow: '0 0 24px rgba(179,136,255,0.45)',
  },
  typography: {
    fontSans: '"Inter", "SF Pro Display", system-ui, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"SF Mono", "Fira Code", monospace',
    headingFont: 'sans',
    xs: '10px',
    sm: '12px',
    base: '14px',
    md: '16px',
    lg: '18px',
    xl: '22px',
    '2xl': '28px',
    '3xl': '36px',
    '4xl': '48px',
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    tight: 1.1,
    normal: 1.5,
    relaxed: 1.7,
    tight_ls: '-0.02em',
    normal_ls: '0em',
    wide_ls: '0.02em',
    wider_ls: '0.05em',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '20px',
    maxWidth: '480px',
    navHeight: '64px',
    headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '8px', md: '12px', lg: '16px', xl: '24px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 12px rgba(0,0,0,0.5)',
    md: '0 4px 24px rgba(0,0,0,0.6)',
    lg: '0 8px 40px rgba(124,77,255,0.25)',
    xl: '0 16px 64px rgba(124,77,255,0.35)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.4)',
  },
  animations: {
    duration: { fast: '150ms', base: '250ms', slow: '400ms' },
    easing: {
      ease: 'cubic-bezier(0.4,0,0.2,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.34,1.56,0.64,1)',
    },
    fade: '250ms',
  },
  layout: {
    variant: 'minimal',
    navPosition: 'top',
    sidebarStyle: 'none',
    navBarStyle: 'none',
    statLayout: 'hero-stat',
    contentLayout: 'cards-masonry',
    sidebarWidth: '0px',
    sidebarCollapsedWidth: '0px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '480px',
  },
  components: {
    button: {
      style: 'pill',
      radius: '9999px',
      fontWeight: 600,
      letterSpacing: '0em',
      textTransform: 'none',
      paddingX: '24px',
      paddingY: '14px',
    },
    card: {
      style: 'glass',
      radius: '16px',
      padding: '20px',
      shadow: '0 4px 24px rgba(0,0,0,0.5)',
      borderWidth: '1px',
      accentWidth: '0px',
      accentPosition: 'none',
    },
    table: {
      style: 'minimal',
      headerBg: '#1E1740',
      rowHoverBg: 'rgba(179,136,255,0.06)',
      borderColor: '#2A2350',
      cellPaddingX: '16px',
      cellPaddingY: '14px',
      fontSize: '14px',
      headerFontSize: '11px',
      stripeColor: 'rgba(255,255,255,0.02)',
      density: 'relaxed',
    },
    form: {
      style: 'filled',
      radius: '12px',
      borderColor: '#3D3470',
      focusBorderColor: '#B388FF',
      bg: '#1E1740',
      labelSize: '11px',
      inputSize: '16px',
    },
    modal: {
      style: 'bottom-sheet',
      radius: '24px',
      shadow: '0 -8px 40px rgba(0,0,0,0.7)',
      overlayColor: 'rgba(13,11,30,0.85)',
      overlayBlur: 'blur(12px)',
    },
    badge: {
      style: 'pill',
      radius: '9999px',
      fontSize: '11px',
      fontWeight: 600,
    },
    nav: {
      style: 'filled',
      itemRadius: '9999px',
      itemPadding: '12px 20px',
      fontSize: '11px',
      iconSize: 22,
      showLabels: true,
      showIcons: true,
      activeIndicator: 'bg-fill',
      groupHeaders: false,
    },
    stat: {
      radius: '16px',
      valueFont: 'sans',
      valueFontSize: '42px',
      accentPosition: 'none',
      accentWidth: '0px',
      bgStyle: 'glass',
    },
  },
  meta: {
    version: '1.0.0',
    author: 'Theme Engine',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-22',
  },
};

export default theme;
