import { Theme } from '../types';

const theme: Theme = {
  id: 'aurelius',
  name: 'Aurelius',
  description: 'Deep warm charcoal with restrained champagne gold — private banking refinement for executive dashboards.',
  category: 'luxury',
  tags: ['luxury', 'dark', 'gold', 'serif', 'executive', 'cinematic'],
  brand: {
    name: 'Aurelius',
    tagline: '',
    logo: '',
    logoAlt: 'Aurelius',
    favicon: '',
    stripeColors: ['#C9A84C', '#2C2820', '#C9A84C', '#2C2820', '#C9A84C'],
    stripeHeight: 1,
  },
  colors: {
    bg: '#0D0C0A',
    bgSecondary: '#121009',
    bgTertiary: '#181510',
    panel: '#181510',
    panelSecondary: '#1E1B15',
    tint: '#221F19',
    ink: '#F2E8D5',
    ink2: '#C4B49A',
    ink3: '#7A6E5C',
    rule: '#2C2820',
    ruleStrong: '#3D3628',
    primary: '#C9A84C',
    primaryHover: '#B8985A',
    primaryText: '#0D0C0A',
    accent1: '#C9A84C',
    accent2: '#8B7355',
    accent3: '#6B8C5E',
    accent4: '#7C6E8A',
    accent5: '#5C7A8A',
    alert: '#A0522D',
    warn: '#B8860B',
    ok: '#6B8C5E',
    info: '#5C7A8A',
    navBg: '#0D0C0A',
    navText: '#7A6E5C',
    navActiveText: '#C9A84C',
    navActiveBg: 'transparent',
    navActiveBorder: '#C9A84C',
    headerBg: '#0D0C0A',
    headerText: '#F2E8D5',
    headerBorder: '#2C2820',
  },
  typography: {
    fontSans: '"Cormorant Garamond", "Playfair Display", Georgia, serif',
    fontSerif: '"Cormorant Garamond", Georgia, serif',
    fontMono: '"IBM Plex Mono", monospace',
    xs: '10px',
    sm: '12px',
    base: '14px',
    md: '15px',
    lg: '18px',
    xl: '22px',
    '2xl': '28px',
    '3xl': '36px',
    '4xl': '48px',
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    tight: 1.15,
    normal: 1.5,
    relaxed: 1.8,
    tight_ls: '-0.02em',
    normal_ls: '0em',
    wide_ls: '0.08em',
    wider_ls: '0.25em',
    headingFont: 'serif',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '40px',
    maxWidth: '1200px',
    navHeight: '64px',
    headerHeight: '72px',
  },
  borders: {
    radius: {
      none: '0',
      sm: '0px',
      md: '0px',
      lg: '0px',
      xl: '2px',
      full: '9999px',
    },
    width: {
      thin: '1px',
      base: '1px',
      thick: '2px',
    },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 8px rgba(0,0,0,0.4)',
    md: '0 4px 20px rgba(0,0,0,0.5)',
    lg: '0 8px 40px rgba(0,0,0,0.6)',
    xl: '0 16px 64px rgba(0,0,0,0.7)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.5)',
  },
  animations: {
    duration: {
      fast: '300ms',
      base: '600ms',
      slow: '1000ms',
    },
    easing: {
      ease: 'cubic-bezier(0.25,0.1,0.25,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.25,0.1,0.25,1)',
    },
    fade: '600ms',
  },
  layout: {
    variant: 'top-nav',
    navPosition: 'top',
    sidebarStyle: 'none',
    navBarStyle: 'underline',
    statLayout: 'grid-2',
    contentLayout: 'table-top-charts-below',
    sidebarWidth: '0px',
    sidebarCollapsedWidth: '0px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '1200px',
  },
  components: {
    button: {
      style: 'outline',
      radius: '0px',
      fontWeight: 400,
      letterSpacing: '0.2em',
      textTransform: 'uppercase',
      paddingX: '24px',
      paddingY: '10px',
      borderWidth: '1px',
      borderColor: '#C9A84C',
    },
    card: {
      style: 'bordered',
      radius: '0px',
      padding: '32px',
      shadow: 'none',
      borderWidth: '1px',
      accentWidth: '1px',
      accentPosition: 'top',
    },
    table: {
      style: 'minimal',
      headerBg: 'transparent',
      rowHoverBg: '#221F19',
      borderColor: '#2C2820',
      cellPaddingX: '20px',
      cellPaddingY: '16px',
      fontSize: '14px',
      headerFontSize: '10px',
      stripeColor: 'transparent',
      density: 'relaxed',
    },
    nav: {
      style: 'underline',
      itemRadius: '0px',
      itemPadding: '14px 20px',
      fontSize: '14px',
      iconSize: 0,
      showLabels: true,
      showIcons: false,
      activeIndicator: 'underline',
      groupHeaders: false,
    },
    stat: {
      radius: '0px',
      valueFont: 'serif',
      valueFontSize: '52px',
      accentPosition: 'top',
      accentWidth: '1px',
      bgStyle: 'solid',
    },
    form: {
      style: 'underlined',
      radius: '0px',
      borderColor: '#2C2820',
      focusBorderColor: '#C9A84C',
      bg: 'transparent',
      labelSize: '10px',
      inputSize: '14px',
    },
    modal: {
      style: 'centered',
      radius: '0px',
      shadow: '0 20px 80px rgba(0,0,0,0.8)',
      overlayColor: 'rgba(0,0,0,0.9)',
      overlayBlur: 'blur(4px)',
    },
    badge: {
      style: 'outline',
      radius: '0px',
      fontSize: '10px',
      fontWeight: 400,
    },
  },
  meta: {
    version: '1.1.0',
    author: 'Theme Engine',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
    isDefault: false,
  },
};

export default theme;
