import type { Theme } from '../types';

// Inspired by Akbank Mobile — bold crimson red brand color on white,
// high-contrast typography, powerful banking identity, clean mobile UI.

const theme: Theme = {
  id: 'banking-red',
  name: 'Banking Red',
  description: 'Bold crimson banking identity — high-contrast red on white, clean card layouts, strong brand presence. Inspired by Turkish/global consumer banking apps.',
  category: 'finance',
  tags: ['finance', 'banking', 'mobile', 'red', 'bold', 'consumer', 'clean'],
  brand: {
    name: 'Banking Red',
    tagline: 'Your money, made simple.',
    logo: '',
    logoAlt: 'Banking Red',
    favicon: '',
    stripeColors: ['#D32F2F', '#FFFFFF', '#D32F2F', '#FFFFFF', '#D32F2F'],
    stripeHeight: 4,
  },
  colors: {
    bg: '#FFFFFF',
    bgSecondary: '#F5F5F5',
    bgTertiary: '#EEEEEE',
    panel: '#FFFFFF',
    panelSecondary: '#FAFAFA',
    tint: 'rgba(211,47,47,0.06)',
    ink: '#111111',
    ink2: '#555555',
    ink3: '#999999',
    rule: '#E0E0E0',
    ruleStrong: '#BDBDBD',
    primary: '#D32F2F',
    primaryHover: '#B71C1C',
    primaryText: '#FFFFFF',
    accent1: '#D32F2F',
    accent2: '#00C853',
    accent3: '#FF6F00',
    accent4: '#1565C0',
    accent5: '#6A1B9A',
    alert: '#D32F2F',
    warn: '#FF6F00',
    ok: '#00C853',
    info: '#1565C0',
    navBg: '#FFFFFF',
    navText: '#999999',
    navActiveText: '#D32F2F',
    navActiveBg: 'rgba(211,47,47,0.06)',
    navActiveBorder: '#D32F2F',
    headerBg: '#D32F2F',
    headerText: '#FFFFFF',
    headerBorder: '#B71C1C',
  },
  typography: {
    fontSans: '"Inter", "Helvetica Neue", Arial, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px',
    sm: '12px',
    base: '14px',
    md: '16px',
    lg: '18px',
    xl: '22px',
    '2xl': '28px',
    '3xl': '36px',
    '4xl': '48px',
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    tight: 1.1,
    normal: 1.5,
    relaxed: 1.7,
    tight_ls: '-0.02em',
    normal_ls: '0em',
    wide_ls: '0.02em',
    wider_ls: '0.05em',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '20px',
    maxWidth: '480px',
    navHeight: '60px',
    headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '6px', md: '10px', lg: '14px', xl: '20px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 1px 8px rgba(0,0,0,0.08)',
    md: '0 4px 20px rgba(0,0,0,0.10)',
    lg: '0 8px 32px rgba(0,0,0,0.12)',
    xl: '0 16px 48px rgba(0,0,0,0.15)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.05)',
  },
  animations: {
    duration: { fast: '120ms', base: '200ms', slow: '350ms' },
    easing: {
      ease: 'cubic-bezier(0.4,0,0.2,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.34,1.56,0.64,1)',
    },
    fade: '200ms',
  },
  layout: {
    variant: 'minimal',
    navPosition: 'top',
    sidebarStyle: 'none',
    navBarStyle: 'none',
    statLayout: 'row-scroll',
    contentLayout: 'cards-masonry',
    sidebarWidth: '0px',
    sidebarCollapsedWidth: '0px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '480px',
  },
  components: {
    button: {
      style: 'rounded',
      radius: '10px',
      fontWeight: 600,
      letterSpacing: '0em',
      textTransform: 'none',
      paddingX: '24px',
      paddingY: '14px',
    },
    card: {
      style: 'elevated',
      radius: '12px',
      padding: '20px',
      shadow: '0 2px 12px rgba(0,0,0,0.08)',
      borderWidth: '0px',
      accentWidth: '0px',
      accentPosition: 'none',
    },
    table: {
      style: 'minimal',
      headerBg: '#F5F5F5',
      rowHoverBg: 'rgba(211,47,47,0.04)',
      borderColor: '#E0E0E0',
      cellPaddingX: '16px',
      cellPaddingY: '14px',
      fontSize: '14px',
      headerFontSize: '11px',
      stripeColor: 'rgba(0,0,0,0.02)',
      density: 'relaxed',
    },
    form: {
      style: 'outlined',
      radius: '10px',
      borderColor: '#E0E0E0',
      focusBorderColor: '#D32F2F',
      bg: '#FFFFFF',
      labelSize: '12px',
      inputSize: '16px',
    },
    modal: {
      style: 'bottom-sheet',
      radius: '20px',
      shadow: '0 -4px 32px rgba(0,0,0,0.12)',
      overlayColor: 'rgba(0,0,0,0.5)',
      overlayBlur: 'blur(8px)',
    },
    badge: {
      style: 'pill',
      radius: '9999px',
      fontSize: '11px',
      fontWeight: 600,
    },
    nav: {
      style: 'underline',
      itemRadius: '0px',
      itemPadding: '12px 8px',
      fontSize: '10px',
      iconSize: 22,
      showLabels: true,
      showIcons: true,
      activeIndicator: 'underline',
      groupHeaders: false,
    },
    stat: {
      radius: '12px',
      valueFont: 'sans',
      valueFontSize: '36px',
      accentPosition: 'none',
      accentWidth: '0px',
      bgStyle: 'solid',
    },
  },
  meta: {
    version: '1.0.0',
    author: 'Theme Engine',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-22',
  },
};

export default theme;
