import type { Theme } from '../types';

// Inspired by personal budget/expense tracker apps — fresh mint green on white,
// pie charts, spending categories, daily expense cards, money-positive design.

const theme: Theme = {
  id: 'budget-mint',
  name: 'Budget Mint',
  description: 'Fresh mint personal finance — spending pie charts, category tags, daily expense cards, money-positive palette. Inspired by budget & expense tracker apps.',
  category: 'finance',
  tags: ['finance', 'budget', 'mobile', 'mint', 'green', 'expense', 'tracker', 'clean'],
  brand: {
    name: 'Budget Mint',
    tagline: 'Spend smarter.',
    logo: '',
    logoAlt: 'Budget Mint',
    favicon: '',
    stripeColors: ['#00C896', '#FFFFFF', '#00A87E', '#FFFFFF', '#00C896'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#FFFFFF',
    bgSecondary: '#F0FBF8',
    bgTertiary: '#E0F7F2',
    panel: '#FFFFFF',
    panelSecondary: '#F0FBF8',
    tint: 'rgba(0,200,150,0.06)',
    ink: '#0A1F1A',
    ink2: '#2A6055',
    ink3: '#7ABAAC',
    rule: '#C8EEE8',
    ruleStrong: '#A8DECF',
    primary: '#00C896',
    primaryHover: '#00A87E',
    primaryText: '#FFFFFF',
    accent1: '#00C896',
    accent2: '#FF6B6B',
    accent3: '#FFD700',
    accent4: '#5B8DEF',
    accent5: '#B47FEB',
    alert: '#FF6B6B',
    warn: '#FFD700',
    ok: '#00C896',
    info: '#5B8DEF',
    navBg: '#FFFFFF',
    navText: '#7ABAAC',
    navActiveText: '#00C896',
    navActiveBg: 'rgba(0,200,150,0.08)',
    navActiveBorder: '#00C896',
    headerBg: '#FFFFFF',
    headerText: '#0A1F1A',
    headerBorder: '#C8EEE8',
  },
  typography: {
    fontSans: '"DM Sans", "Inter", system-ui, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"JetBrains Mono", monospace',
    headingFont: 'sans',
    xs: '10px', sm: '12px', base: '14px', md: '16px', lg: '18px', xl: '22px',
    '2xl': '28px', '3xl': '36px', '4xl': '48px',
    regular: 400, medium: 500, semibold: 600, bold: 700,
    tight: 1.15, normal: 1.55, relaxed: 1.75,
    tight_ls: '-0.01em', normal_ls: '0em', wide_ls: '0.02em', wider_ls: '0.05em',
  },
  spacing: {
    '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px',
    '6': '24px', '8': '32px', '10': '40px', '12': '48px', '16': '64px',
    '20': '80px', '24': '96px',
    contentPadding: '20px', maxWidth: '480px', navHeight: '60px', headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '8px', md: '12px', lg: '16px', xl: '24px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 1px 8px rgba(0,200,150,0.08)',
    md: '0 4px 20px rgba(0,200,150,0.10)',
    lg: '0 8px 32px rgba(0,200,150,0.14)',
    xl: '0 16px 48px rgba(0,200,150,0.18)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.04)',
  },
  animations: {
    duration: { fast: '120ms', base: '220ms', slow: '380ms' },
    easing: { ease: 'cubic-bezier(0.4,0,0.2,1)', easeIn: 'cubic-bezier(0.4,0,1,1)', easeOut: 'cubic-bezier(0,0,0.2,1)', spring: 'cubic-bezier(0.34,1.56,0.64,1)' },
    fade: '220ms',
  },
  layout: {
    variant: 'minimal', navPosition: 'top', sidebarStyle: 'none', navBarStyle: 'none',
    statLayout: 'row-scroll', contentLayout: 'cards-masonry',
    sidebarWidth: '0px', sidebarCollapsedWidth: '0px',
    headerSticky: true, navSticky: true, contentMaxWidth: '480px',
  },
  components: {
    button: { style: 'pill', radius: '9999px', fontWeight: 600, letterSpacing: '0em', textTransform: 'none', paddingX: '24px', paddingY: '14px' },
    card: { style: 'elevated', radius: '16px', padding: '20px', shadow: '0 2px 16px rgba(0,200,150,0.08)', borderWidth: '0px', accentWidth: '0px', accentPosition: 'none' },
    table: { style: 'minimal', headerBg: '#F0FBF8', rowHoverBg: 'rgba(0,200,150,0.04)', borderColor: '#C8EEE8', cellPaddingX: '16px', cellPaddingY: '12px', fontSize: '14px', headerFontSize: '11px', stripeColor: 'rgba(0,0,0,0.02)', density: 'normal' },
    form: { style: 'outlined', radius: '12px', borderColor: '#A8DECF', focusBorderColor: '#00C896', bg: '#FFFFFF', labelSize: '12px', inputSize: '16px' },
    modal: { style: 'bottom-sheet', radius: '24px', shadow: '0 -4px 40px rgba(0,0,0,0.10)', overlayColor: 'rgba(0,0,0,0.5)', overlayBlur: 'blur(8px)' },
    badge: { style: 'pill', radius: '9999px', fontSize: '11px', fontWeight: 600 },
    nav: { style: 'minimal', itemRadius: '0px', itemPadding: '12px 8px', fontSize: '10px', iconSize: 22, showLabels: true, showIcons: true, activeIndicator: 'underline', groupHeaders: false },
    stat: { radius: '12px', valueFont: 'sans', valueFontSize: '38px', accentPosition: 'none', accentWidth: '0px', bgStyle: 'solid' },
  },
  meta: { version: '1.0.0', author: 'Theme Engine', createdAt: '2026-06-22', updatedAt: '2026-06-22' },
};

export default theme;
