import type { Theme } from '../types';

// Inspired by education language/learning apps — bright white background,
// colorful accent palette, gamification badges, progress bars, playful rounded UI.

const theme: Theme = {
  id: 'edu-playful',
  name: 'Edu Playful',
  description: 'Bright white gamified learning — colorful accents, rounded UI, XP bars, badge system. Inspired by language learning & EdTech mobile apps.',
  category: 'education',
  tags: ['education', 'mobile', 'bright', 'colorful', 'gamified', 'learning', 'kids', 'playful'],
  brand: {
    name: 'Edu Playful',
    tagline: 'Learning is an adventure.',
    logo: '',
    logoAlt: 'Edu Playful',
    favicon: '',
    stripeColors: ['#58CC02', '#1CB0F6', '#FF4B4B', '#FFDE00', '#CE82FF'],
    stripeHeight: 4,
  },
  colors: {
    bg: '#FFFFFF',
    bgSecondary: '#F7F7F7',
    bgTertiary: '#F0F0F0',
    panel: '#FFFFFF',
    panelSecondary: '#FAFAFA',
    tint: 'rgba(88,204,2,0.08)',
    ink: '#3C3C3C',
    ink2: '#777777',
    ink3: '#AFAFAF',
    rule: '#E5E5E5',
    ruleStrong: '#CCCCCC',
    primary: '#58CC02',
    primaryHover: '#49AB00',
    primaryText: '#FFFFFF',
    accent1: '#58CC02',
    accent2: '#1CB0F6',
    accent3: '#FF4B4B',
    accent4: '#FFDE00',
    accent5: '#CE82FF',
    alert: '#FF4B4B',
    warn: '#FFDE00',
    ok: '#58CC02',
    info: '#1CB0F6',
    navBg: '#FFFFFF',
    navText: '#AFAFAF',
    navActiveText: '#58CC02',
    navActiveBg: 'rgba(88,204,2,0.08)',
    navActiveBorder: '#58CC02',
    headerBg: '#FFFFFF',
    headerText: '#3C3C3C',
    headerBorder: '#E5E5E5',
  },
  typography: {
    fontSans: '"Nunito", "Rounded Mplus 1c", system-ui, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px', sm: '12px', base: '15px', md: '17px', lg: '20px', xl: '24px',
    '2xl': '30px', '3xl': '40px', '4xl': '52px',
    regular: 400, medium: 600, semibold: 700, bold: 800,
    tight: 1.1, normal: 1.55, relaxed: 1.75,
    tight_ls: '-0.01em', normal_ls: '0em', wide_ls: '0.02em', wider_ls: '0.04em',
  },
  spacing: {
    '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px',
    '6': '24px', '8': '32px', '10': '40px', '12': '48px', '16': '64px',
    '20': '80px', '24': '96px',
    contentPadding: '20px', maxWidth: '480px', navHeight: '64px', headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '8px', md: '14px', lg: '20px', xl: '28px', full: '9999px' },
    width: { thin: '1px', base: '2px', thick: '3px' },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 8px rgba(0,0,0,0.08)',
    md: '0 4px 16px rgba(0,0,0,0.10)',
    lg: '0 6px 24px rgba(88,204,2,0.20)',
    xl: '0 12px 40px rgba(88,204,2,0.25)',
    inner: 'inset 0 2px 4px rgba(0,0,0,0.06)',
  },
  animations: {
    duration: { fast: '150ms', base: '250ms', slow: '400ms' },
    easing: { ease: 'cubic-bezier(0.4,0,0.2,1)', easeIn: 'cubic-bezier(0.4,0,1,1)', easeOut: 'cubic-bezier(0,0,0.2,1)', spring: 'cubic-bezier(0.34,1.56,0.64,1)' },
    fade: '250ms',
  },
  layout: {
    variant: 'minimal', navPosition: 'top', sidebarStyle: 'none', navBarStyle: 'none',
    statLayout: 'row-scroll', contentLayout: 'cards-masonry',
    sidebarWidth: '0px', sidebarCollapsedWidth: '0px',
    headerSticky: true, navSticky: true, contentMaxWidth: '480px',
  },
  components: {
    button: { style: 'pill', radius: '9999px', fontWeight: 800, letterSpacing: '0.01em', textTransform: 'none', paddingX: '28px', paddingY: '16px' },
    card: { style: 'elevated', radius: '20px', padding: '20px', shadow: '0 4px 16px rgba(0,0,0,0.08)', borderWidth: '2px', accentWidth: '0px', accentPosition: 'none' },
    table: { style: 'minimal', headerBg: '#F7F7F7', rowHoverBg: 'rgba(88,204,2,0.04)', borderColor: '#E5E5E5', cellPaddingX: '16px', cellPaddingY: '14px', fontSize: '14px', headerFontSize: '11px', stripeColor: 'rgba(0,0,0,0.02)', density: 'relaxed' },
    form: { style: 'outlined', radius: '14px', borderColor: '#CCCCCC', focusBorderColor: '#58CC02', bg: '#FFFFFF', labelSize: '12px', inputSize: '16px' },
    modal: { style: 'bottom-sheet', radius: '28px', shadow: '0 -4px 40px rgba(0,0,0,0.12)', overlayColor: 'rgba(0,0,0,0.5)', overlayBlur: 'blur(8px)' },
    badge: { style: 'pill', radius: '9999px', fontSize: '11px', fontWeight: 700 },
    nav: { style: 'minimal', itemRadius: '0px', itemPadding: '12px 8px', fontSize: '10px', iconSize: 24, showLabels: true, showIcons: true, activeIndicator: 'underline', groupHeaders: false },
    stat: { radius: '16px', valueFont: 'sans', valueFontSize: '40px', accentPosition: 'top', accentWidth: '4px', bgStyle: 'solid' },
  },
  meta: { version: '1.0.0', author: 'Theme Engine', createdAt: '2026-06-22', updatedAt: '2026-06-22' },
};

export default theme;
