import { Theme } from '../types';

const theme: Theme = {
  id: 'enterprise',
  name: 'Enterprise',
  description: 'Navy authority with dense tables — the gold standard for large enterprise deployments.',
  category: 'corporate',
  tags: ['corporate', 'navy', 'dense', 'tables', 'enterprise', 'professional'],
  brand: {
    name: 'Enterprise',
    tagline: '',
    logo: '',
    logoAlt: 'Enterprise',
    favicon: '',
    stripeColors: ['#1E3A5F', '#C9A84C', '#1E3A5F', '#C9A84C', '#1E3A5F'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#F2F4F7',
    bgSecondary: '#E8ECF2',
    bgTertiary: '#DCE2EC',
    panel: '#FFFFFF',
    panelSecondary: '#F8F9FB',
    tint: '#EEF2F8',
    ink: '#0D1B2E',
    ink2: '#2C3E52',
    ink3: '#6B7C8D',
    rule: '#D8E0EC',
    ruleStrong: '#B8C4D4',
    primary: '#1E3A5F',
    primaryHover: '#162D4A',
    primaryText: '#FFFFFF',
    accent1: '#C9A84C',
    accent2: '#2E7D32',
    accent3: '#C62828',
    accent4: '#1565C0',
    accent5: '#6A1B9A',
    alert: '#C62828',
    warn: '#E65100',
    ok: '#2E7D32',
    info: '#1565C0',
    navBg: '#1E3A5F',
    navText: '#7A9BC0',
    navActiveText: '#FFFFFF',
    navActiveBg: '#162D4A',
    navActiveBorder: '#C9A84C',
    headerBg: '#FFFFFF',
    headerText: '#0D1B2E',
    headerBorder: '#D8E0EC',
  },
  typography: {
    fontSans: '"IBM Plex Sans", -apple-system, sans-serif',
    fontSerif: '"IBM Plex Serif", Georgia, serif',
    fontMono: '"IBM Plex Mono", monospace',
    xs: '10px',
    sm: '11px',
    base: '13px',
    md: '14px',
    lg: '16px',
    xl: '18px',
    '2xl': '22px',
    '3xl': '28px',
    '4xl': '36px',
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    tight: 1.2,
    normal: 1.5,
    relaxed: 1.75,
    tight_ls: '-0.01em',
    normal_ls: '0em',
    wide_ls: '0.05em',
    wider_ls: '0.08em',
    headingFont: 'serif',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '24px',
    maxWidth: '1440px',
    navHeight: '48px',
    headerHeight: '56px',
  },
  borders: {
    radius: {
      none: '0',
      sm: '2px',
      md: '4px',
      lg: '6px',
      xl: '8px',
      full: '9999px',
    },
    width: {
      thin: '1px',
      base: '2px',
      thick: '3px',
    },
  },
  shadows: {
    none: 'none',
    sm: '0 1px 4px rgba(13,27,46,0.08)',
    md: '0 4px 12px rgba(13,27,46,0.1)',
    lg: '0 8px 24px rgba(13,27,46,0.14)',
    xl: '0 16px 48px rgba(13,27,46,0.18)',
    inner: 'inset 0 1px 3px rgba(13,27,46,0.06)',
  },
  animations: {
    duration: {
      fast: '100ms',
      base: '180ms',
      slow: '300ms',
    },
    easing: {
      ease: 'cubic-bezier(0.4,0,0.2,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.34,1.56,0.64,1)',
    },
    fade: '180ms',
  },
  layout: {
    variant: 'enterprise',
    navPosition: 'left',
    sidebarStyle: 'dark-solid',
    navBarStyle: 'none',
    statLayout: 'grid-4',
    contentLayout: 'table-primary',
    sidebarWidth: '220px',
    sidebarCollapsedWidth: '56px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '1440px',
  },
  components: {
    button: {
      style: 'sharp',
      radius: '3px',
      fontWeight: 700,
      letterSpacing: '0.8px',
      textTransform: 'uppercase',
      paddingX: '16px',
      paddingY: '8px',
    },
    card: {
      style: 'bordered',
      radius: '4px',
      padding: '20px',
      shadow: 'none',
      borderWidth: '1px',
      accentWidth: '3px',
      accentPosition: 'left',
    },
    table: {
      style: 'striped',
      headerBg: '#EEF2F8',
      rowHoverBg: '#E8EDF5',
      borderColor: '#D8E0EC',
      cellPaddingX: '14px',
      cellPaddingY: '10px',
      fontSize: '12px',
      headerFontSize: '9px',
      stripeColor: '#F8F9FB',
      density: 'compact',
    },
    nav: {
      style: 'filled',
      itemRadius: '2px',
      itemPadding: '10px 16px',
      fontSize: '13px',
      iconSize: 15,
      showLabels: true,
      showIcons: true,
      activeIndicator: 'border-left',
      groupHeaders: true,
    },
    stat: {
      radius: '4px',
      valueFont: 'serif',
      valueFontSize: '32px',
      accentPosition: 'left',
      accentWidth: '3px',
      bgStyle: 'solid',
    },
    form: {
      style: 'outlined',
      radius: '2px',
      borderColor: '#D8E0EC',
      focusBorderColor: '#1E3A5F',
      bg: '#FFFFFF',
      labelSize: '9px',
      inputSize: '12px',
    },
    modal: {
      style: 'centered',
      radius: '4px',
      shadow: '0 16px 48px rgba(13,27,46,0.2)',
      overlayColor: 'rgba(13,27,46,0.5)',
      overlayBlur: 'blur(2px)',
    },
    badge: {
      style: 'square',
      radius: '2px',
      fontSize: '9px',
      fontWeight: 700,
    },
  },
  meta: {
    version: '1.0.0',
    author: 'Theme Engine',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
    isDefault: false,
  },
};

export default theme;
