import type { Theme } from '../types';

// Inspired by ABNB Mobile / savings apps — warm beige/cream outer shell,
// white card panels, navy blue brand, clean login-first UX, trust-signaling design.

const theme: Theme = {
  id: 'fintech-savings',
  name: 'Fintech Savings',
  description: 'Warm beige savings app — white card panels, navy brand, trust-first clean UX. Inspired by credit union & savings mobile apps.',
  category: 'finance',
  tags: ['finance', 'savings', 'mobile', 'beige', 'navy', 'clean', 'trust'],
  brand: {
    name: 'Fintech Savings',
    tagline: 'Save smarter, every day.',
    logo: '',
    logoAlt: 'Fintech Savings',
    favicon: '',
    stripeColors: ['#1E3A6E', '#E8DDD0', '#F5C842', '#E8DDD0', '#1E3A6E'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#E8DDD0',
    bgSecondary: '#DDD0C0',
    bgTertiary: '#D0C0AD',
    panel: '#FFFFFF',
    panelSecondary: '#FAF8F5',
    tint: 'rgba(30,58,110,0.06)',
    ink: '#111827',
    ink2: '#4B5563',
    ink3: '#9CA3AF',
    rule: '#D1C9BD',
    ruleStrong: '#B8AFA5',
    primary: '#1E3A6E',
    primaryHover: '#152C54',
    primaryText: '#FFFFFF',
    accent1: '#1E3A6E',
    accent2: '#F5C842',
    accent3: '#16A34A',
    accent4: '#0EA5E9',
    accent5: '#DC2626',
    alert: '#DC2626',
    warn: '#F5C842',
    ok: '#16A34A',
    info: '#0EA5E9',
    navBg: '#FFFFFF',
    navText: '#9CA3AF',
    navActiveText: '#1E3A6E',
    navActiveBg: 'rgba(30,58,110,0.06)',
    navActiveBorder: '#1E3A6E',
    headerBg: '#E8DDD0',
    headerText: '#111827',
    headerBorder: '#D1C9BD',
  },
  typography: {
    fontSans: '"Inter", "Helvetica Neue", Arial, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px', sm: '12px', base: '14px', md: '16px', lg: '18px', xl: '22px',
    '2xl': '28px', '3xl': '36px', '4xl': '48px',
    regular: 400, medium: 500, semibold: 600, bold: 700,
    tight: 1.1, normal: 1.55, relaxed: 1.75,
    tight_ls: '-0.02em', normal_ls: '0em', wide_ls: '0.02em', wider_ls: '0.05em',
  },
  spacing: {
    '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px',
    '6': '24px', '8': '32px', '10': '40px', '12': '48px', '16': '64px',
    '20': '80px', '24': '96px',
    contentPadding: '20px', maxWidth: '480px', navHeight: '60px', headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '6px', md: '12px', lg: '16px', xl: '24px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 1px 8px rgba(0,0,0,0.06)',
    md: '0 4px 20px rgba(0,0,0,0.08)',
    lg: '0 8px 32px rgba(0,0,0,0.10)',
    xl: '0 16px 48px rgba(0,0,0,0.12)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.04)',
  },
  animations: {
    duration: { fast: '120ms', base: '220ms', slow: '380ms' },
    easing: { ease: 'cubic-bezier(0.4,0,0.2,1)', easeIn: 'cubic-bezier(0.4,0,1,1)', easeOut: 'cubic-bezier(0,0,0.2,1)', spring: 'cubic-bezier(0.34,1.56,0.64,1)' },
    fade: '220ms',
  },
  layout: {
    variant: 'minimal', navPosition: 'top', sidebarStyle: 'none', navBarStyle: 'none',
    statLayout: 'row-scroll', contentLayout: 'cards-masonry',
    sidebarWidth: '0px', sidebarCollapsedWidth: '0px',
    headerSticky: true, navSticky: true, contentMaxWidth: '480px',
  },
  components: {
    button: { style: 'rounded', radius: '12px', fontWeight: 600, letterSpacing: '0em', textTransform: 'none', paddingX: '24px', paddingY: '14px' },
    card: { style: 'elevated', radius: '16px', padding: '20px', shadow: '0 2px 16px rgba(0,0,0,0.08)', borderWidth: '0px', accentWidth: '0px', accentPosition: 'none' },
    table: { style: 'minimal', headerBg: '#FAF8F5', rowHoverBg: 'rgba(30,58,110,0.04)', borderColor: '#D1C9BD', cellPaddingX: '16px', cellPaddingY: '14px', fontSize: '14px', headerFontSize: '11px', stripeColor: 'rgba(0,0,0,0.02)', density: 'relaxed' },
    form: { style: 'outlined', radius: '10px', borderColor: '#D1C9BD', focusBorderColor: '#1E3A6E', bg: '#FFFFFF', labelSize: '12px', inputSize: '16px' },
    modal: { style: 'bottom-sheet', radius: '20px', shadow: '0 -4px 32px rgba(0,0,0,0.10)', overlayColor: 'rgba(0,0,0,0.5)', overlayBlur: 'blur(8px)' },
    badge: { style: 'pill', radius: '9999px', fontSize: '11px', fontWeight: 600 },
    nav: { style: 'minimal', itemRadius: '0px', itemPadding: '12px 8px', fontSize: '10px', iconSize: 22, showLabels: true, showIcons: true, activeIndicator: 'underline', groupHeaders: false },
    stat: { radius: '12px', valueFont: 'sans', valueFontSize: '36px', accentPosition: 'none', accentWidth: '0px', bgStyle: 'solid' },
  },
  meta: { version: '1.0.0', author: 'Theme Engine', createdAt: '2026-06-22', updatedAt: '2026-06-22' },
};

export default theme;
