import type { Theme } from '../types';

// Inspired by 10K Runner / Fitness apps — bright yellow-green gradient, bold uppercase,
// energetic workout tracking, progress rings, dark navy contrast for readability.

const theme: Theme = {
  id: 'fitness-energy',
  name: 'Fitness Energy',
  description: 'Electric yellow-green workout energy — bold uppercase, progress rings, dark navy contrast. Inspired by running & fitness tracking apps.',
  category: 'health',
  tags: ['health', 'fitness', 'mobile', 'yellow', 'green', 'energy', 'workout', 'bold'],
  brand: {
    name: 'Fitness Energy',
    tagline: 'Push your limits.',
    logo: '',
    logoAlt: 'Fitness Energy',
    favicon: '',
    stripeColors: ['#CDDC39', '#1A237E', '#76FF03', '#1A237E', '#CDDC39'],
    stripeHeight: 4,
  },
  colors: {
    bg: '#0D1B2A',
    bgSecondary: '#1A2A3D',
    bgTertiary: '#243447',
    panel: '#1E3250',
    panelSecondary: '#162640',
    tint: 'rgba(205,220,57,0.10)',
    ink: '#FFFFFF',
    ink2: '#B0BEC5',
    ink3: '#607D8B',
    rule: '#243447',
    ruleStrong: '#344F66',
    primary: '#CDDC39',
    primaryHover: '#C0CA33',
    primaryText: '#0D1B2A',
    accent1: '#CDDC39',
    accent2: '#76FF03',
    accent3: '#FF6F00',
    accent4: '#00E5FF',
    accent5: '#FF4081',
    alert: '#FF4081',
    warn: '#FF6F00',
    ok: '#76FF03',
    info: '#00E5FF',
    navBg: '#0D1B2A',
    navText: '#607D8B',
    navActiveText: '#CDDC39',
    navActiveBg: 'rgba(205,220,57,0.10)',
    navActiveBorder: '#CDDC39',
    headerBg: '#0D1B2A',
    headerText: '#FFFFFF',
    headerBorder: '#243447',
    buttonGradient: 'linear-gradient(135deg, #CDDC39 0%, #76FF03 100%)',
  },
  typography: {
    fontSans: '"Inter", "Barlow", system-ui, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px',
    sm: '12px',
    base: '14px',
    md: '16px',
    lg: '18px',
    xl: '22px',
    '2xl': '28px',
    '3xl': '38px',
    '4xl': '52px',
    regular: 400,
    medium: 500,
    semibold: 700,
    bold: 800,
    tight: 1.0,
    normal: 1.5,
    relaxed: 1.7,
    tight_ls: '-0.01em',
    normal_ls: '0.02em',
    wide_ls: '0.06em',
    wider_ls: '0.12em',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '20px',
    maxWidth: '480px',
    navHeight: '64px',
    headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '8px', md: '12px', lg: '16px', xl: '24px', full: '9999px' },
    width: { thin: '1px', base: '2px', thick: '3px' },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 12px rgba(0,0,0,0.4)',
    md: '0 4px 24px rgba(0,0,0,0.5)',
    lg: '0 8px 40px rgba(205,220,57,0.20)',
    xl: '0 16px 64px rgba(205,220,57,0.30)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.4)',
  },
  animations: {
    duration: { fast: '100ms', base: '180ms', slow: '320ms' },
    easing: {
      ease: 'cubic-bezier(0.4,0,0.2,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.34,1.56,0.64,1)',
    },
    fade: '180ms',
  },
  layout: {
    variant: 'minimal',
    navPosition: 'top',
    sidebarStyle: 'none',
    navBarStyle: 'none',
    statLayout: 'hero-stat',
    contentLayout: 'cards-masonry',
    sidebarWidth: '0px',
    sidebarCollapsedWidth: '0px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '480px',
  },
  components: {
    button: {
      style: 'pill',
      radius: '9999px',
      fontWeight: 800,
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      paddingX: '28px',
      paddingY: '16px',
    },
    card: {
      style: 'glass',
      radius: '16px',
      padding: '20px',
      shadow: '0 4px 20px rgba(0,0,0,0.4)',
      borderWidth: '1px',
      accentWidth: '0px',
      accentPosition: 'none',
    },
    table: {
      style: 'minimal',
      headerBg: '#1E3250',
      rowHoverBg: 'rgba(205,220,57,0.06)',
      borderColor: '#243447',
      cellPaddingX: '16px',
      cellPaddingY: '14px',
      fontSize: '14px',
      headerFontSize: '11px',
      stripeColor: 'rgba(255,255,255,0.02)',
      density: 'relaxed',
    },
    form: {
      style: 'filled',
      radius: '12px',
      borderColor: '#344F66',
      focusBorderColor: '#CDDC39',
      bg: '#1E3250',
      labelSize: '11px',
      inputSize: '16px',
    },
    modal: {
      style: 'bottom-sheet',
      radius: '24px',
      shadow: '0 -8px 40px rgba(0,0,0,0.7)',
      overlayColor: 'rgba(13,27,42,0.85)',
      overlayBlur: 'blur(12px)',
    },
    badge: {
      style: 'pill',
      radius: '9999px',
      fontSize: '10px',
      fontWeight: 700,
    },
    nav: {
      style: 'minimal',
      itemRadius: '0px',
      itemPadding: '12px 8px',
      fontSize: '10px',
      iconSize: 24,
      showLabels: true,
      showIcons: true,
      activeIndicator: 'underline',
      groupHeaders: false,
    },
    stat: {
      radius: '16px',
      valueFont: 'sans',
      valueFontSize: '44px',
      accentPosition: 'none',
      accentWidth: '0px',
      bgStyle: 'glass',
    },
  },
  meta: {
    version: '1.0.0',
    author: 'Theme Engine',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-22',
  },
};

export default theme;
