import type { Theme } from '../types';

// Inspired by 5-Minute Journal — warm cream/beige editorial, serif headlines,
// paper-like texture, journaling habit tracker, warm ochre accent.

const theme: Theme = {
  id: 'journal-cream',
  name: 'Journal Cream',
  description: 'Warm beige editorial journaling — serif headlines, cream paper feel, ochre accents, mindful calm aesthetic. Inspired by mindfulness & daily habit apps.',
  category: 'health',
  tags: ['health', 'wellness', 'mobile', 'cream', 'beige', 'serif', 'editorial', 'journal', 'calm'],
  brand: {
    name: 'Journal Cream',
    tagline: 'Build beautiful habits.',
    logo: '',
    logoAlt: 'Journal Cream',
    favicon: '',
    stripeColors: ['#C8A96E', '#EDE0CF', '#A0845C', '#EDE0CF', '#C8A96E'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#F5EFE6',
    bgSecondary: '#EDE0CF',
    bgTertiary: '#E3D4BF',
    panel: '#FFFFFF',
    panelSecondary: '#FAF5ED',
    tint: 'rgba(200,169,110,0.10)',
    ink: '#1C1410',
    ink2: '#5C4A35',
    ink3: '#9B8370',
    rule: '#D9C9B4',
    ruleStrong: '#C4AF97',
    primary: '#8B5E3C',
    primaryHover: '#6D4526',
    primaryText: '#FFFFFF',
    accent1: '#C8A96E',
    accent2: '#7BA05B',
    accent3: '#C0784A',
    accent4: '#6B8FAE',
    accent5: '#B06080',
    alert: '#C0784A',
    warn: '#C8A96E',
    ok: '#7BA05B',
    info: '#6B8FAE',
    navBg: '#F5EFE6',
    navText: '#9B8370',
    navActiveText: '#8B5E3C',
    navActiveBg: 'rgba(139,94,60,0.08)',
    navActiveBorder: '#8B5E3C',
    headerBg: '#F5EFE6',
    headerText: '#1C1410',
    headerBorder: '#D9C9B4',
  },
  typography: {
    fontSans: '"DM Sans", "Helvetica Neue", Arial, sans-serif',
    fontSerif: '"Lora", "Playfair Display", "Georgia", serif',
    fontMono: '"JetBrains Mono", monospace',
    headingFont: 'serif',
    xs: '10px',
    sm: '12px',
    base: '15px',
    md: '17px',
    lg: '20px',
    xl: '24px',
    '2xl': '30px',
    '3xl': '40px',
    '4xl': '52px',
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    tight: 1.15,
    normal: 1.65,
    relaxed: 1.85,
    tight_ls: '-0.01em',
    normal_ls: '0em',
    wide_ls: '0.03em',
    wider_ls: '0.07em',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '24px',
    maxWidth: '480px',
    navHeight: '60px',
    headerHeight: '52px',
  },
  borders: {
    radius: { none: '0', sm: '6px', md: '10px', lg: '16px', xl: '24px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 1px 8px rgba(100,70,40,0.08)',
    md: '0 4px 20px rgba(100,70,40,0.10)',
    lg: '0 8px 32px rgba(100,70,40,0.12)',
    xl: '0 16px 48px rgba(100,70,40,0.15)',
    inner: 'inset 0 1px 3px rgba(100,70,40,0.08)',
  },
  animations: {
    duration: { fast: '150ms', base: '280ms', slow: '480ms' },
    easing: {
      ease: 'cubic-bezier(0.4,0,0.2,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.34,1.56,0.64,1)',
    },
    fade: '280ms',
  },
  layout: {
    variant: 'minimal',
    navPosition: 'top',
    sidebarStyle: 'none',
    navBarStyle: 'none',
    statLayout: 'row-scroll',
    contentLayout: 'cards-masonry',
    sidebarWidth: '0px',
    sidebarCollapsedWidth: '0px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '480px',
  },
  components: {
    button: {
      style: 'rounded',
      radius: '10px',
      fontWeight: 600,
      letterSpacing: '0.01em',
      textTransform: 'none',
      paddingX: '24px',
      paddingY: '14px',
    },
    card: {
      style: 'elevated',
      radius: '16px',
      padding: '24px',
      shadow: '0 2px 16px rgba(100,70,40,0.08)',
      borderWidth: '0px',
      accentWidth: '0px',
      accentPosition: 'none',
    },
    table: {
      style: 'minimal',
      headerBg: '#EDE0CF',
      rowHoverBg: 'rgba(139,94,60,0.04)',
      borderColor: '#D9C9B4',
      cellPaddingX: '16px',
      cellPaddingY: '14px',
      fontSize: '14px',
      headerFontSize: '11px',
      stripeColor: 'rgba(200,169,110,0.04)',
      density: 'relaxed',
    },
    form: {
      style: 'outlined',
      radius: '10px',
      borderColor: '#D9C9B4',
      focusBorderColor: '#8B5E3C',
      bg: '#FFFFFF',
      labelSize: '12px',
      inputSize: '15px',
    },
    modal: {
      style: 'bottom-sheet',
      radius: '24px',
      shadow: '0 -4px 40px rgba(100,70,40,0.15)',
      overlayColor: 'rgba(28,20,16,0.5)',
      overlayBlur: 'blur(8px)',
    },
    badge: {
      style: 'pill',
      radius: '9999px',
      fontSize: '11px',
      fontWeight: 600,
    },
    nav: {
      style: 'minimal',
      itemRadius: '0px',
      itemPadding: '12px 8px',
      fontSize: '10px',
      iconSize: 22,
      showLabels: true,
      showIcons: true,
      activeIndicator: 'underline',
      groupHeaders: false,
    },
    stat: {
      radius: '16px',
      valueFont: 'serif',
      valueFontSize: '40px',
      accentPosition: 'top',
      accentWidth: '3px',
      bgStyle: 'solid',
    },
  },
  meta: {
    version: '1.0.0',
    author: 'Theme Engine',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-22',
  },
};

export default theme;
