import type { Theme } from '../types';

// Inspired by news/media apps — clean white editorial, high-contrast black headlines,
// article card layout, category chips, reading mode typography.

const theme: Theme = {
  id: 'news-reader',
  name: 'News Reader',
  description: 'Clean editorial news — high-contrast headlines, article cards, category chips, reading mode. Inspired by news & media mobile apps.',
  category: 'minimal',
  tags: ['news', 'media', 'mobile', 'white', 'editorial', 'reading', 'minimal', 'clean'],
  brand: {
    name: 'News Reader',
    tagline: 'Stay informed.',
    logo: '',
    logoAlt: 'News Reader',
    favicon: '',
    stripeColors: ['#1A1A1A', '#FFFFFF', '#CC0000', '#FFFFFF', '#1A1A1A'],
    stripeHeight: 4,
  },
  colors: {
    bg: '#FFFFFF',
    bgSecondary: '#F8F8F8',
    bgTertiary: '#F0F0F0',
    panel: '#FFFFFF',
    panelSecondary: '#F8F8F8',
    tint: 'rgba(204,0,0,0.05)',
    ink: '#0A0A0A',
    ink2: '#4A4A4A',
    ink3: '#9A9A9A',
    rule: '#E8E8E8',
    ruleStrong: '#D0D0D0',
    primary: '#CC0000',
    primaryHover: '#AA0000',
    primaryText: '#FFFFFF',
    accent1: '#CC0000',
    accent2: '#0066CC',
    accent3: '#FF8800',
    accent4: '#009933',
    accent5: '#7700AA',
    alert: '#CC0000',
    warn: '#FF8800',
    ok: '#009933',
    info: '#0066CC',
    navBg: '#FFFFFF',
    navText: '#9A9A9A',
    navActiveText: '#0A0A0A',
    navActiveBg: 'rgba(0,0,0,0.05)',
    navActiveBorder: '#0A0A0A',
    headerBg: '#FFFFFF',
    headerText: '#0A0A0A',
    headerBorder: '#E8E8E8',
  },
  typography: {
    fontSans: '"Inter", "Helvetica Neue", Arial, sans-serif',
    fontSerif: '"Merriweather", "Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'serif',
    xs: '10px', sm: '12px', base: '15px', md: '17px', lg: '20px', xl: '24px',
    '2xl': '30px', '3xl': '40px', '4xl': '54px',
    regular: 400, medium: 500, semibold: 600, bold: 700,
    tight: 1.15, normal: 1.65, relaxed: 1.85,
    tight_ls: '-0.01em', normal_ls: '0em', wide_ls: '0.02em', wider_ls: '0.05em',
  },
  spacing: {
    '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px',
    '6': '24px', '8': '32px', '10': '40px', '12': '48px', '16': '64px',
    '20': '80px', '24': '96px',
    contentPadding: '20px', maxWidth: '480px', navHeight: '52px', headerHeight: '52px',
  },
  borders: {
    radius: { none: '0', sm: '4px', md: '8px', lg: '12px', xl: '16px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '3px' },
  },
  shadows: {
    none: 'none',
    sm: '0 1px 6px rgba(0,0,0,0.06)',
    md: '0 2px 12px rgba(0,0,0,0.08)',
    lg: '0 4px 24px rgba(0,0,0,0.10)',
    xl: '0 8px 40px rgba(0,0,0,0.12)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.04)',
  },
  animations: {
    duration: { fast: '100ms', base: '180ms', slow: '300ms' },
    easing: { ease: 'cubic-bezier(0.4,0,0.2,1)', easeIn: 'cubic-bezier(0.4,0,1,1)', easeOut: 'cubic-bezier(0,0,0.2,1)', spring: 'cubic-bezier(0.34,1.56,0.64,1)' },
    fade: '180ms',
  },
  layout: {
    variant: 'minimal', navPosition: 'top', sidebarStyle: 'none', navBarStyle: 'none',
    statLayout: 'row-scroll', contentLayout: 'cards-masonry',
    sidebarWidth: '0px', sidebarCollapsedWidth: '0px',
    headerSticky: true, navSticky: true, contentMaxWidth: '480px',
  },
  components: {
    button: { style: 'rounded', radius: '6px', fontWeight: 600, letterSpacing: '0em', textTransform: 'none', paddingX: '20px', paddingY: '10px' },
    card: { style: 'flat', radius: '0px', padding: '16px', shadow: 'none', borderWidth: '1px', accentWidth: '0px', accentPosition: 'none' },
    table: { style: 'minimal', headerBg: '#F8F8F8', rowHoverBg: 'rgba(0,0,0,0.03)', borderColor: '#E8E8E8', cellPaddingX: '16px', cellPaddingY: '12px', fontSize: '14px', headerFontSize: '11px', stripeColor: 'rgba(0,0,0,0.02)', density: 'normal' },
    form: { style: 'outlined', radius: '8px', borderColor: '#D0D0D0', focusBorderColor: '#0A0A0A', bg: '#FFFFFF', labelSize: '12px', inputSize: '16px' },
    modal: { style: 'bottom-sheet', radius: '16px', shadow: '0 -4px 32px rgba(0,0,0,0.10)', overlayColor: 'rgba(0,0,0,0.5)', overlayBlur: 'blur(4px)' },
    badge: { style: 'pill', radius: '4px', fontSize: '11px', fontWeight: 600 },
    nav: { style: 'underline', itemRadius: '0px', itemPadding: '12px 8px', fontSize: '10px', iconSize: 22, showLabels: true, showIcons: true, activeIndicator: 'underline', groupHeaders: false },
    stat: { radius: '8px', valueFont: 'serif', valueFontSize: '36px', accentPosition: 'left', accentWidth: '3px', bgStyle: 'solid' },
  },
  meta: { version: '1.0.0', author: 'Theme Engine', createdAt: '2026-06-22', updatedAt: '2026-06-22' },
};

export default theme;
