import { Theme } from '../types';

const theme: Theme = {
  id: 'obsidian',
  name: 'Obsidian',
  description: 'Deep space dark with neon cyan — built for high-density data and real-time monitoring.',
  category: 'tech',
  tags: ['dark', 'neon', 'cyber', 'monitoring', 'dense'],
  brand: {
    name: 'Obsidian',
    tagline: '',
    logo: '',
    logoAlt: 'Obsidian',
    favicon: '',
    stripeColors: ['#00BCD4', '#006064', '#00BCD4', '#004D40', '#00ACC1'],
    stripeHeight: 2,
  },
  colors: {
    bg: '#0A0E1A',
    bgSecondary: '#080C17',
    bgTertiary: '#060912',
    panel: '#0F1627',
    panelSecondary: '#0D1420',
    tint: '#111C2E',
    ink: '#E8F4FD',
    ink2: '#8BA7C7',
    ink3: '#4A6A8A',
    rule: '#1A2540',
    ruleStrong: '#2A3A60',
    primary: '#00BCD4',
    primaryHover: '#00ACC1',
    primaryText: '#000000',
    accent1: '#00BCD4',
    accent2: '#FF6B6B',
    accent3: '#FFD93D',
    accent4: '#6BCB77',
    accent5: '#845EC2',
    alert: '#FF4757',
    warn: '#FFA502',
    ok: '#6BCB77',
    info: '#00BCD4',
    navBg: '#060912',
    navText: '#4A6A8A',
    navActiveText: '#00BCD4',
    navActiveBg: '#001A22',
    navActiveBorder: '#00BCD4',
    headerBg: '#060912',
    headerText: '#E8F4FD',
    headerBorder: '#1A2540',
    buttonGradient: 'linear-gradient(135deg, #00BCD4, #006064)',
    buttonGlow: '0 0 20px rgba(0,188,212,0.5), 0 0 40px rgba(0,188,212,0.2)',
  },
  typography: {
    fontSans: '"Inter", -apple-system, sans-serif',
    fontSerif: '"Inter", sans-serif',
    fontMono: '"JetBrains Mono", "Fira Code", monospace',
    xs: '9px',
    sm: '11px',
    base: '13px',
    md: '14px',
    lg: '16px',
    xl: '18px',
    '2xl': '22px',
    '3xl': '28px',
    '4xl': '36px',
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    tight: 1.2,
    normal: 1.5,
    relaxed: 1.75,
    tight_ls: '-0.02em',
    normal_ls: '0em',
    wide_ls: '0.05em',
    wider_ls: '0.1em',
    headingFont: 'mono',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '24px',
    maxWidth: '1600px',
    navHeight: '52px',
    headerHeight: '60px',
  },
  borders: {
    radius: {
      none: '0',
      sm: '3px',
      md: '6px',
      lg: '8px',
      xl: '12px',
      full: '9999px',
    },
    width: {
      thin: '1px',
      base: '2px',
      thick: '3px',
    },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 8px rgba(0,0,0,0.4)',
    md: '0 4px 16px rgba(0,0,0,0.5)',
    lg: '0 8px 32px rgba(0,0,0,0.6)',
    xl: '0 20px 60px rgba(0,0,0,0.7)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.4)',
  },
  animations: {
    duration: {
      fast: '100ms',
      base: '200ms',
      slow: '350ms',
    },
    easing: {
      ease: 'cubic-bezier(0.4,0,0.2,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.34,1.56,0.64,1)',
    },
    fade: '200ms',
  },
  layout: {
    variant: 'dashboard',
    navPosition: 'left',
    sidebarStyle: 'minimal-icon',
    navBarStyle: 'none',
    statLayout: 'row-scroll',
    contentLayout: 'chart-left-table-right',
    sidebarWidth: '52px',
    sidebarCollapsedWidth: '52px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '1600px',
  },
  components: {
    button: {
      style: 'glow',
      radius: '4px',
      fontWeight: 700,
      letterSpacing: '1px',
      textTransform: 'uppercase',
      paddingX: '18px',
      paddingY: '9px',
    },
    card: {
      style: 'neon',
      radius: '6px',
      padding: '20px',
      shadow: '0 4px 24px rgba(0,188,212,0.08)',
      borderWidth: '1px',
      accentWidth: '2px',
      accentPosition: 'left',
    },
    table: {
      style: 'compact',
      headerBg: '#0F1627',
      rowHoverBg: '#111C2E',
      borderColor: '#1A2540',
      cellPaddingX: '14px',
      cellPaddingY: '8px',
      fontSize: '12px',
      headerFontSize: '9px',
      stripeColor: '#0D1420',
      density: 'compact',
    },
    nav: {
      style: 'minimal',
      itemRadius: '6px',
      itemPadding: '12px 0',
      fontSize: '12px',
      iconSize: 18,
      showLabels: false,
      showIcons: true,
      activeIndicator: 'border-right',
      groupHeaders: false,
    },
    stat: {
      radius: '6px',
      valueFont: 'mono',
      valueFontSize: '28px',
      accentPosition: 'top',
      accentWidth: '2px',
      bgStyle: 'gradient',
    },
    form: {
      style: 'outlined',
      radius: '4px',
      borderColor: '#1A2540',
      focusBorderColor: '#00BCD4',
      bg: '#0F1627',
      labelSize: '9px',
      inputSize: '12px',
    },
    modal: {
      style: 'centered',
      radius: '8px',
      shadow: '0 20px 60px rgba(0,0,0,0.6)',
      overlayColor: 'rgba(6,9,18,0.85)',
      overlayBlur: 'blur(8px)',
    },
    badge: {
      style: 'glow',
      radius: '4px',
      fontSize: '9px',
      fontWeight: 700,
    },
  },
  meta: {
    version: '1.0.0',
    author: 'Theme Engine',
    createdAt: '2026-06-17',
    updatedAt: '2026-06-17',
  },
};

export default theme;
