import type { Theme } from '../types';

// Inspired by 1Password / productivity apps — clean white/cream, blue accent,
// list-first layout, clear hierarchy, security & trust visual language.

const theme: Theme = {
  id: 'productivity-focus',
  name: 'Productivity Focus',
  description: 'Clean white productivity — blue accent, list-first hierarchy, trust-signaling design. Inspired by password manager & productivity mobile apps.',
  category: 'productivity',
  tags: ['productivity', 'mobile', 'white', 'blue', 'clean', 'list', 'focus', 'trust'],
  brand: {
    name: 'Productivity Focus',
    tagline: 'Stay organized, stay focused.',
    logo: '',
    logoAlt: 'Productivity Focus',
    favicon: '',
    stripeColors: ['#0770E3', '#FFFFFF', '#1A56DB', '#FFFFFF', '#0770E3'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#F9FAFB',
    bgSecondary: '#F3F4F6',
    bgTertiary: '#E5E7EB',
    panel: '#FFFFFF',
    panelSecondary: '#F9FAFB',
    tint: 'rgba(7,112,227,0.06)',
    ink: '#111827',
    ink2: '#4B5563',
    ink3: '#9CA3AF',
    rule: '#E5E7EB',
    ruleStrong: '#D1D5DB',
    primary: '#0770E3',
    primaryHover: '#0558C2',
    primaryText: '#FFFFFF',
    accent1: '#0770E3',
    accent2: '#059669',
    accent3: '#D97706',
    accent4: '#7C3AED',
    accent5: '#DC2626',
    alert: '#DC2626',
    warn: '#D97706',
    ok: '#059669',
    info: '#0770E3',
    navBg: '#FFFFFF',
    navText: '#9CA3AF',
    navActiveText: '#0770E3',
    navActiveBg: 'rgba(7,112,227,0.06)',
    navActiveBorder: '#0770E3',
    headerBg: '#FFFFFF',
    headerText: '#111827',
    headerBorder: '#E5E7EB',
  },
  typography: {
    fontSans: '"Inter", "Helvetica Neue", Arial, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"JetBrains Mono", "SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px', sm: '12px', base: '14px', md: '16px', lg: '18px', xl: '22px',
    '2xl': '28px', '3xl': '36px', '4xl': '48px',
    regular: 400, medium: 500, semibold: 600, bold: 700,
    tight: 1.2, normal: 1.55, relaxed: 1.75,
    tight_ls: '-0.01em', normal_ls: '0em', wide_ls: '0.02em', wider_ls: '0.05em',
  },
  spacing: {
    '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px',
    '6': '24px', '8': '32px', '10': '40px', '12': '48px', '16': '64px',
    '20': '80px', '24': '96px',
    contentPadding: '20px', maxWidth: '480px', navHeight: '60px', headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '6px', md: '10px', lg: '14px', xl: '20px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 1px 6px rgba(0,0,0,0.06)',
    md: '0 4px 16px rgba(0,0,0,0.08)',
    lg: '0 8px 32px rgba(0,0,0,0.10)',
    xl: '0 16px 48px rgba(0,0,0,0.12)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.04)',
  },
  animations: {
    duration: { fast: '120ms', base: '200ms', slow: '350ms' },
    easing: { ease: 'cubic-bezier(0.4,0,0.2,1)', easeIn: 'cubic-bezier(0.4,0,1,1)', easeOut: 'cubic-bezier(0,0,0.2,1)', spring: 'cubic-bezier(0.34,1.56,0.64,1)' },
    fade: '200ms',
  },
  layout: {
    variant: 'minimal', navPosition: 'top', sidebarStyle: 'none', navBarStyle: 'none',
    statLayout: 'row-scroll', contentLayout: 'table-primary',
    sidebarWidth: '0px', sidebarCollapsedWidth: '0px',
    headerSticky: true, navSticky: true, contentMaxWidth: '480px',
  },
  components: {
    button: { style: 'rounded', radius: '8px', fontWeight: 600, letterSpacing: '0em', textTransform: 'none', paddingX: '20px', paddingY: '12px' },
    card: { style: 'elevated', radius: '10px', padding: '16px', shadow: '0 2px 12px rgba(0,0,0,0.06)', borderWidth: '0px', accentWidth: '0px', accentPosition: 'none' },
    table: { style: 'minimal', headerBg: '#F3F4F6', rowHoverBg: 'rgba(7,112,227,0.04)', borderColor: '#E5E7EB', cellPaddingX: '16px', cellPaddingY: '12px', fontSize: '14px', headerFontSize: '11px', stripeColor: 'rgba(0,0,0,0.02)', density: 'normal' },
    form: { style: 'outlined', radius: '8px', borderColor: '#D1D5DB', focusBorderColor: '#0770E3', bg: '#FFFFFF', labelSize: '12px', inputSize: '16px' },
    modal: { style: 'bottom-sheet', radius: '16px', shadow: '0 -4px 32px rgba(0,0,0,0.10)', overlayColor: 'rgba(0,0,0,0.5)', overlayBlur: 'blur(8px)' },
    badge: { style: 'pill', radius: '9999px', fontSize: '11px', fontWeight: 600 },
    nav: { style: 'minimal', itemRadius: '0px', itemPadding: '12px 8px', fontSize: '10px', iconSize: 22, showLabels: true, showIcons: true, activeIndicator: 'underline', groupHeaders: false },
    stat: { radius: '10px', valueFont: 'sans', valueFontSize: '36px', accentPosition: 'none', accentWidth: '0px', bgStyle: 'solid' },
  },
  meta: { version: '1.0.0', author: 'Theme Engine', createdAt: '2026-06-22', updatedAt: '2026-06-22' },
};

export default theme;
