import type { Theme } from '../types';

// Inspired by shopping/e-commerce apps — bright white with pink accent,
// product grid cards, wishlist hearts, price tags, checkout flow design.

const theme: Theme = {
  id: 'shopping-pink',
  name: 'Shopping Pink',
  description: 'Bright white e-commerce — pink accent, product grid, wishlist hearts, price tags. Inspired by fashion & shopping mobile apps.',
  category: 'startup',
  tags: ['shopping', 'ecommerce', 'mobile', 'pink', 'white', 'product', 'fashion', 'consumer'],
  brand: {
    name: 'Shopping Pink',
    tagline: 'Find your style.',
    logo: '',
    logoAlt: 'Shopping Pink',
    favicon: '',
    stripeColors: ['#E91E8C', '#FFFFFF', '#F06292', '#FFFFFF', '#E91E8C'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#FFFFFF',
    bgSecondary: '#FFF5FA',
    bgTertiary: '#FFE8F2',
    panel: '#FFFFFF',
    panelSecondary: '#FFF5FA',
    tint: 'rgba(233,30,140,0.06)',
    ink: '#1A0010',
    ink2: '#6B2050',
    ink3: '#C080A0',
    rule: '#F5D0E5',
    ruleStrong: '#EAB0CF',
    primary: '#E91E8C',
    primaryHover: '#C2185B',
    primaryText: '#FFFFFF',
    accent1: '#E91E8C',
    accent2: '#FF6B6B',
    accent3: '#FFD700',
    accent4: '#7B1FA2',
    accent5: '#00BFA5',
    alert: '#FF1744',
    warn: '#FFD700',
    ok: '#00BFA5',
    info: '#7B1FA2',
    navBg: '#FFFFFF',
    navText: '#C080A0',
    navActiveText: '#E91E8C',
    navActiveBg: 'rgba(233,30,140,0.06)',
    navActiveBorder: '#E91E8C',
    headerBg: '#FFFFFF',
    headerText: '#1A0010',
    headerBorder: '#F5D0E5',
    buttonGradient: 'linear-gradient(135deg, #E91E8C 0%, #F06292 100%)',
  },
  typography: {
    fontSans: '"Poppins", "Nunito", system-ui, sans-serif',
    fontSerif: '"Playfair Display", "Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px', sm: '12px', base: '14px', md: '16px', lg: '18px', xl: '22px',
    '2xl': '28px', '3xl': '36px', '4xl': '48px',
    regular: 400, medium: 500, semibold: 600, bold: 700,
    tight: 1.1, normal: 1.55, relaxed: 1.75,
    tight_ls: '-0.01em', normal_ls: '0em', wide_ls: '0.01em', wider_ls: '0.04em',
  },
  spacing: {
    '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px',
    '6': '24px', '8': '32px', '10': '40px', '12': '48px', '16': '64px',
    '20': '80px', '24': '96px',
    contentPadding: '16px', maxWidth: '480px', navHeight: '60px', headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '8px', md: '12px', lg: '16px', xl: '24px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 10px rgba(233,30,140,0.06)',
    md: '0 4px 20px rgba(233,30,140,0.08)',
    lg: '0 8px 32px rgba(233,30,140,0.12)',
    xl: '0 16px 48px rgba(233,30,140,0.16)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.04)',
  },
  animations: {
    duration: { fast: '120ms', base: '220ms', slow: '380ms' },
    easing: { ease: 'cubic-bezier(0.4,0,0.2,1)', easeIn: 'cubic-bezier(0.4,0,1,1)', easeOut: 'cubic-bezier(0,0,0.2,1)', spring: 'cubic-bezier(0.34,1.56,0.64,1)' },
    fade: '220ms',
  },
  layout: {
    variant: 'minimal', navPosition: 'top', sidebarStyle: 'none', navBarStyle: 'none',
    statLayout: 'row-scroll', contentLayout: 'cards-masonry',
    sidebarWidth: '0px', sidebarCollapsedWidth: '0px',
    headerSticky: true, navSticky: true, contentMaxWidth: '480px',
  },
  components: {
    button: { style: 'pill', radius: '9999px', fontWeight: 700, letterSpacing: '0em', textTransform: 'none', paddingX: '24px', paddingY: '14px' },
    card: { style: 'elevated', radius: '16px', padding: '0px', shadow: '0 2px 16px rgba(0,0,0,0.06)', borderWidth: '0px', accentWidth: '0px', accentPosition: 'none' },
    table: { style: 'minimal', headerBg: '#FFF5FA', rowHoverBg: 'rgba(233,30,140,0.03)', borderColor: '#F5D0E5', cellPaddingX: '16px', cellPaddingY: '12px', fontSize: '14px', headerFontSize: '11px', stripeColor: 'rgba(0,0,0,0.02)', density: 'relaxed' },
    form: { style: 'outlined', radius: '12px', borderColor: '#EAB0CF', focusBorderColor: '#E91E8C', bg: '#FFFFFF', labelSize: '12px', inputSize: '16px' },
    modal: { style: 'bottom-sheet', radius: '24px', shadow: '0 -4px 40px rgba(0,0,0,0.10)', overlayColor: 'rgba(0,0,0,0.5)', overlayBlur: 'blur(8px)' },
    badge: { style: 'pill', radius: '9999px', fontSize: '11px', fontWeight: 600 },
    nav: { style: 'minimal', itemRadius: '0px', itemPadding: '12px 8px', fontSize: '10px', iconSize: 22, showLabels: true, showIcons: true, activeIndicator: 'underline', groupHeaders: false },
    stat: { radius: '12px', valueFont: 'sans', valueFontSize: '36px', accentPosition: 'none', accentWidth: '0px', bgStyle: 'solid' },
  },
  meta: { version: '1.0.0', author: 'Theme Engine', createdAt: '2026-06-22', updatedAt: '2026-06-22' },
};

export default theme;
