import type { Theme } from '../types';

// Inspired by Belong social app — deep black with teal accent, photo-heavy story circles,
// bottom tab navigation, community feed cards, high-contrast consumer social aesthetic.

const theme: Theme = {
  id: 'social-dark',
  name: 'Social Dark',
  description: 'Pure black social feed — teal accent, photo stories, bottom tab nav, high-contrast community aesthetic. Inspired by modern social networking apps.',
  category: 'social',
  tags: ['social', 'dark', 'mobile', 'black', 'teal', 'photo', 'community', 'feed'],
  brand: {
    name: 'Social Dark',
    tagline: 'Find your people.',
    logo: '',
    logoAlt: 'Social Dark',
    favicon: '',
    stripeColors: ['#00BCD4', '#000000', '#00ACC1', '#000000', '#00BCD4'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#000000',
    bgSecondary: '#0A0A0A',
    bgTertiary: '#141414',
    panel: '#1A1A1A',
    panelSecondary: '#121212',
    tint: 'rgba(0,188,212,0.10)',
    ink: '#FFFFFF',
    ink2: '#AAAAAA',
    ink3: '#666666',
    rule: '#222222',
    ruleStrong: '#333333',
    primary: '#00BCD4',
    primaryHover: '#00ACC1',
    primaryText: '#000000',
    accent1: '#00BCD4',
    accent2: '#69F0AE',
    accent3: '#FFD740',
    accent4: '#FF6B6B',
    accent5: '#CF6679',
    alert: '#FF6B6B',
    warn: '#FFD740',
    ok: '#69F0AE',
    info: '#00BCD4',
    navBg: '#000000',
    navText: '#666666',
    navActiveText: '#00BCD4',
    navActiveBg: 'rgba(0,188,212,0.10)',
    navActiveBorder: '#00BCD4',
    headerBg: '#000000',
    headerText: '#FFFFFF',
    headerBorder: '#222222',
  },
  typography: {
    fontSans: '"Inter", "SF Pro Text", system-ui, sans-serif',
    fontSerif: '"Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px',
    sm: '12px',
    base: '14px',
    md: '16px',
    lg: '18px',
    xl: '22px',
    '2xl': '28px',
    '3xl': '36px',
    '4xl': '48px',
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    tight: 1.2,
    normal: 1.5,
    relaxed: 1.7,
    tight_ls: '-0.01em',
    normal_ls: '0em',
    wide_ls: '0.02em',
    wider_ls: '0.05em',
  },
  spacing: {
    '0': '0px',
    '1': '4px',
    '2': '8px',
    '3': '12px',
    '4': '16px',
    '5': '20px',
    '6': '24px',
    '8': '32px',
    '10': '40px',
    '12': '48px',
    '16': '64px',
    '20': '80px',
    '24': '96px',
    contentPadding: '16px',
    maxWidth: '480px',
    navHeight: '60px',
    headerHeight: '52px',
  },
  borders: {
    radius: { none: '0', sm: '6px', md: '10px', lg: '14px', xl: '20px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 12px rgba(0,0,0,0.6)',
    md: '0 4px 24px rgba(0,0,0,0.7)',
    lg: '0 8px 40px rgba(0,188,212,0.20)',
    xl: '0 16px 64px rgba(0,188,212,0.30)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.5)',
  },
  animations: {
    duration: { fast: '120ms', base: '220ms', slow: '380ms' },
    easing: {
      ease: 'cubic-bezier(0.4,0,0.2,1)',
      easeIn: 'cubic-bezier(0.4,0,1,1)',
      easeOut: 'cubic-bezier(0,0,0.2,1)',
      spring: 'cubic-bezier(0.34,1.56,0.64,1)',
    },
    fade: '220ms',
  },
  layout: {
    variant: 'minimal',
    navPosition: 'top',
    sidebarStyle: 'none',
    navBarStyle: 'none',
    statLayout: 'row-scroll',
    contentLayout: 'cards-masonry',
    sidebarWidth: '0px',
    sidebarCollapsedWidth: '0px',
    headerSticky: true,
    navSticky: true,
    contentMaxWidth: '480px',
  },
  components: {
    button: {
      style: 'rounded',
      radius: '9999px',
      fontWeight: 600,
      letterSpacing: '0em',
      textTransform: 'none',
      paddingX: '20px',
      paddingY: '10px',
    },
    card: {
      style: 'flat',
      radius: '12px',
      padding: '16px',
      shadow: 'none',
      borderWidth: '1px',
      accentWidth: '0px',
      accentPosition: 'none',
    },
    table: {
      style: 'minimal',
      headerBg: '#1A1A1A',
      rowHoverBg: 'rgba(0,188,212,0.06)',
      borderColor: '#222222',
      cellPaddingX: '16px',
      cellPaddingY: '14px',
      fontSize: '14px',
      headerFontSize: '11px',
      stripeColor: 'rgba(255,255,255,0.02)',
      density: 'relaxed',
    },
    form: {
      style: 'filled',
      radius: '10px',
      borderColor: '#333333',
      focusBorderColor: '#00BCD4',
      bg: '#1A1A1A',
      labelSize: '12px',
      inputSize: '16px',
    },
    modal: {
      style: 'bottom-sheet',
      radius: '20px',
      shadow: '0 -4px 32px rgba(0,0,0,0.8)',
      overlayColor: 'rgba(0,0,0,0.75)',
      overlayBlur: 'blur(10px)',
    },
    badge: {
      style: 'pill',
      radius: '9999px',
      fontSize: '11px',
      fontWeight: 600,
    },
    nav: {
      style: 'minimal',
      itemRadius: '0px',
      itemPadding: '12px 8px',
      fontSize: '10px',
      iconSize: 24,
      showLabels: true,
      showIcons: true,
      activeIndicator: 'underline',
      groupHeaders: false,
    },
    stat: {
      radius: '12px',
      valueFont: 'sans',
      valueFontSize: '36px',
      accentPosition: 'none',
      accentWidth: '0px',
      bgStyle: 'solid',
    },
  },
  meta: {
    version: '1.0.0',
    author: 'Theme Engine',
    createdAt: '2026-06-22',
    updatedAt: '2026-06-22',
  },
};

export default theme;
