import type { Theme } from '../types';

// Inspired by travel/booking apps — rich destination photography cards,
// coral/teal accent on white, discover grid, booking CTAs, trip planner.

const theme: Theme = {
  id: 'travel-explorer',
  name: 'Travel Explorer',
  description: 'Rich destination photo cards — coral accent, discover grid, booking CTAs, wanderlust palette. Inspired by travel booking & adventure mobile apps.',
  category: 'startup',
  tags: ['travel', 'mobile', 'coral', 'teal', 'photo', 'discovery', 'booking', 'adventure'],
  brand: {
    name: 'Travel Explorer',
    tagline: 'The world awaits.',
    logo: '',
    logoAlt: 'Travel Explorer',
    favicon: '',
    stripeColors: ['#FF6B6B', '#00BFA5', '#4ECDC4', '#FF6B6B', '#00BFA5'],
    stripeHeight: 3,
  },
  colors: {
    bg: '#FFFFFF',
    bgSecondary: '#F7FFFE',
    bgTertiary: '#F0FCFA',
    panel: '#FFFFFF',
    panelSecondary: '#F7FFFE',
    tint: 'rgba(0,191,165,0.06)',
    ink: '#1A2E2B',
    ink2: '#4A6560',
    ink3: '#8AA8A2',
    rule: '#E0F0EE',
    ruleStrong: '#C0DDD9',
    primary: '#FF6B6B',
    primaryHover: '#FF5252',
    primaryText: '#FFFFFF',
    accent1: '#FF6B6B',
    accent2: '#00BFA5',
    accent3: '#FFB300',
    accent4: '#5C6BC0',
    accent5: '#AB47BC',
    alert: '#FF5252',
    warn: '#FFB300',
    ok: '#00BFA5',
    info: '#5C6BC0',
    navBg: '#FFFFFF',
    navText: '#8AA8A2',
    navActiveText: '#FF6B6B',
    navActiveBg: 'rgba(255,107,107,0.06)',
    navActiveBorder: '#FF6B6B',
    headerBg: '#FFFFFF',
    headerText: '#1A2E2B',
    headerBorder: '#E0F0EE',
  },
  typography: {
    fontSans: '"Poppins", "Inter", system-ui, sans-serif',
    fontSerif: '"Playfair Display", "Georgia", serif',
    fontMono: '"SF Mono", monospace',
    headingFont: 'sans',
    xs: '10px', sm: '12px', base: '14px', md: '16px', lg: '18px', xl: '22px',
    '2xl': '28px', '3xl': '36px', '4xl': '48px',
    regular: 400, medium: 500, semibold: 600, bold: 700,
    tight: 1.1, normal: 1.55, relaxed: 1.75,
    tight_ls: '-0.01em', normal_ls: '0em', wide_ls: '0.01em', wider_ls: '0.04em',
  },
  spacing: {
    '0': '0px', '1': '4px', '2': '8px', '3': '12px', '4': '16px', '5': '20px',
    '6': '24px', '8': '32px', '10': '40px', '12': '48px', '16': '64px',
    '20': '80px', '24': '96px',
    contentPadding: '16px', maxWidth: '480px', navHeight: '60px', headerHeight: '56px',
  },
  borders: {
    radius: { none: '0', sm: '8px', md: '14px', lg: '20px', xl: '28px', full: '9999px' },
    width: { thin: '1px', base: '1px', thick: '2px' },
  },
  shadows: {
    none: 'none',
    sm: '0 2px 10px rgba(0,0,0,0.06)',
    md: '0 4px 20px rgba(0,0,0,0.08)',
    lg: '0 8px 32px rgba(255,107,107,0.12)',
    xl: '0 16px 48px rgba(255,107,107,0.16)',
    inner: 'inset 0 1px 3px rgba(0,0,0,0.04)',
  },
  animations: {
    duration: { fast: '150ms', base: '250ms', slow: '400ms' },
    easing: { ease: 'cubic-bezier(0.4,0,0.2,1)', easeIn: 'cubic-bezier(0.4,0,1,1)', easeOut: 'cubic-bezier(0,0,0.2,1)', spring: 'cubic-bezier(0.34,1.56,0.64,1)' },
    fade: '250ms',
  },
  layout: {
    variant: 'minimal', navPosition: 'top', sidebarStyle: 'none', navBarStyle: 'none',
    statLayout: 'row-scroll', contentLayout: 'cards-masonry',
    sidebarWidth: '0px', sidebarCollapsedWidth: '0px',
    headerSticky: true, navSticky: true, contentMaxWidth: '480px',
  },
  components: {
    button: { style: 'pill', radius: '9999px', fontWeight: 600, letterSpacing: '0em', textTransform: 'none', paddingX: '24px', paddingY: '14px' },
    card: { style: 'elevated', radius: '20px', padding: '0px', shadow: '0 4px 20px rgba(0,0,0,0.08)', borderWidth: '0px', accentWidth: '0px', accentPosition: 'none' },
    table: { style: 'minimal', headerBg: '#F7FFFE', rowHoverBg: 'rgba(0,191,165,0.04)', borderColor: '#E0F0EE', cellPaddingX: '16px', cellPaddingY: '14px', fontSize: '14px', headerFontSize: '11px', stripeColor: 'rgba(0,0,0,0.02)', density: 'relaxed' },
    form: { style: 'outlined', radius: '12px', borderColor: '#C0DDD9', focusBorderColor: '#00BFA5', bg: '#FFFFFF', labelSize: '12px', inputSize: '16px' },
    modal: { style: 'bottom-sheet', radius: '24px', shadow: '0 -4px 40px rgba(0,0,0,0.10)', overlayColor: 'rgba(0,0,0,0.5)', overlayBlur: 'blur(10px)' },
    badge: { style: 'pill', radius: '9999px', fontSize: '11px', fontWeight: 600 },
    nav: { style: 'minimal', itemRadius: '0px', itemPadding: '12px 8px', fontSize: '10px', iconSize: 22, showLabels: true, showIcons: true, activeIndicator: 'underline', groupHeaders: false },
    stat: { radius: '14px', valueFont: 'sans', valueFontSize: '36px', accentPosition: 'none', accentWidth: '0px', bgStyle: 'solid' },
  },
  meta: { version: '1.0.0', author: 'Theme Engine', createdAt: '2026-06-22', updatedAt: '2026-06-22' },
};

export default theme;
